### ISSUE TITLE
polymer 1.0 Uncaught TypeError: this.mixin is not a function

### ISSUE THREAD

**Issue by SophiaBelkin** [Polymer/polymer#1911]
We are using polymer for our some of the components in our hybrid app. When I upgrade polymer 0.5 to 1.0 I kept seeing this error message: 
polymer-micro.html:401  Uncaught TypeError: this.mixin is not a function

I have no idea what I did wrong. The components are working fine in the demo index files. When I load the component to my project, even just <paper-button> polymer was broken

**Comment by kevinpschaaf** [comment]
Reproduced here: http://jsbin.com/rapoci/edit?html,console,output

Fail conditions:
* Use `polymer-micro.html`
* Include a behavior that has `hostAttributes`

Root cause: `_addHostAttributes` calls `this.mixin`, which is defined in `utils.html` which is only included in `polymer.html` (standard layer).  `mixin` should be moved to be included in `polymer-micro.html`

**Comment by SophiaBelkin** [comment]
Thank a lot!
