### ISSUE TITLE
Closure compiler ERROR - The types of the getter and setter for property 'template' do not match.

### ISSUE THREAD

**Issue by paladox** [Polymer/polymer#5443]
### Description

Hi, im trying out polymer 2.x in gerrit (using https://gerrit-review.googlesource.com/c/gerrit/+/203832 and https://gerrit-review.googlesource.com/c/gerrit/+/202532)

When i checked out 1b5849e5f4b528d5932722bb8c9229a28f1a8c62 `bazel build release` started to fail with:

```
bazel-out/darwin-fastbuild/bin/polygerrit-ui/app/gr-app.js:6136: ERROR - The types of the getter and setter for property 'template' do not match.
      static set template(value) {
                 ^
  ProTip: "CONFLICTING_GETTER_SETTER_TYPE" can be added to the `suppress` attribute of:
  //polygerrit-ui/app:polygerrit_ui_closure_lib

1 error(s), 1 warning(s)
```

This was working on commit 79de83cee042e4f0532804da8b3951b3159bca16 though.

Caused by https://github.com/Polymer/polymer/commit/8882c3db248634403453e2969d1e9e02f5333b48

#### Live Demo

https://jsbin.com/luhaxab/edit

https://glitch.com/edit/#!/polymer-repro?path=my-element.html:2:0

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- Polymer: 2.x (from the 2.x branch)
- webcomponents: v1.3.0

**Comment by paladox** [comment]
Closing this as resolved (https://github.com/Polymer/polymer/pull/5519)
