### ISSUE TITLE
Upgrade to Polymer 1.2.2 broke tests

### ISSUE THREAD

**Issue by ctreatma** [Polymer/polymer#2734]
My team's build system pulled in 1.2.2 for our latest test run and started getting test failures without any code or test changes.  The error is

       this._getEvent is not a function
         <unknown> at       .fire at /components/si-components/bower_components/polymer/polymer.html.js:1312:0
         <unknown> at       focus at /components/si-components/bower_components/iron-test-helpers/mock-interactions.js:110:0

We have confirmed that downgrading to 1.2.1, while keeping all other bower dependency versions the same, fixes the problem.

**Comment by ebidel** [comment]
I also have people reporting 1.2.2 issues over at https://github.com/GoogleWebComponents/google-chart/issues/73.

**Comment by ebidel** [comment]
This is also causing JSON attribute bindings to fail. See https://github.com/GoogleWebComponents/google-chart/issues/73#issuecomment-156607495 in google-chart. The update in https://github.com/Polymer/polymer/commit/a2c51bf11ed650085adde2be835838dfeab83c28 causes the regex to match now. It did not match before.

**Comment by jshcrowthe** [comment]
In upgrading to `v1.2.2` I also saw some issues with IE11. It started throwing `Object doesn't support this action` errors (I can pull up the exact errors if it would be helpful but they are within an app I'm building). I had a hard time isolating and reproducing the bug but since this thread exists I wanted to chime in.

**Comment by JeremybellEU** [comment]
When I finished breakfast I will look at the JSON binding with the regex. Will try to fix my mistake asap.

**Comment by JeremybellEU** [comment]
I derived 2 possible options at https://github.com/Polymer/polymer/pull/2711#issuecomment-156697654

**Comment by JeremybellEU** [comment]
@jshcrowthe were the errors `Object doesn't support property or method 'querySelectorAll'`? These seem to pop up in the latest build on master (after merging #2737) https://travis-ci.org/Polymer/polymer/jobs/91055533 and should be solved after fixing https://github.com/webcomponents/webcomponentsjs/issues/443

**Comment by jshcrowthe** [comment]
@JeremybellEU The error I am getting is below (I took a screenshot from SauceLabs):

![screen shot 2015-11-14 at 12 52 19 pm](https://cloud.githubusercontent.com/assets/5588878/11165537/2eea83ae-8acf-11e5-864a-5b146bad7283.png)

This code is found here: 
https://github.com/Polymer/polymer/blob/master/src/standard/utils.html#L245-L248

Introduced in #2686

**Comment by sorvell** [comment]
There are a few of issues here that we're working on addressing asap.

* The reported problem (`this._getEvent is not a function`) was caused by `iron-test-helpers` and was fixed in https://github.com/PolymerElements/iron-test-helpers/releases/tag/v1.1.0.

* The `Object doesn't support this action` is specific to IE and due to an incompatibility between Polymer and webcomponentsjs. We'll be doing a release to fix it today.

* https://github.com/GoogleWebComponents/google-chart/issues/73#issuecomment-156607495 is being investigated and will be fixed it asap.

**Comment by joineral32-cengage** [comment]
We also started receiving errors on non-Chrome browser test runs when our CI build started resolving the v1.2.2 tag of this. I have not yet tracked down the specific error, but several of our tests are consistently failing with v1.2.2 and consistently passing with v1.2.1. I will post more specifics as I uncover them.

**Comment by ebidel** [comment]
As a data point, some of my tests started breaking because of timing changes introduced in iron-selector: https://github.com/PolymerElements/iron-selector/commit/92b0bbc31ef7dbb9bbbd1beb0db75877e3babcca. Can you check if an earlier version of that element fixes your issue? There are a lot of elements that rely on its functionality.

**Comment by joineral32-cengage** [comment]
That is a good point. A number of the tests that were having issues did involve components using iron-pages, which uses IronSelectableBehavior. I will revert to an earlier copy of iron-selector and see if that fixes things.

**Comment by ebidel** [comment]
@cdata for the fyi on iron-selector

**Comment by cdata** [comment]
@ebidel @joineral32-cengage Yeah, unfortunately there was a lot of unintended collateral damage from that `iron-selector` change. We're still picking up the pieces, although if something actually broke it would be good to have an issue to follow.

**Comment by ebidel** [comment]
@cdata Gladly I haven't seen any app break. In reality, everything (bindings, distribution) settle to their final, correct values. The unexpectedness comes up in tests where an assumption about an iron-selector-enabled element is made. For example, querying its `.items` property is no longer a getter that returns a live node list. Now, `.items` is populated at `.observeNodes` timing. For tests, this means introducing `this.nextTick` calls or waiting for `iron-items-changed`

**Comment by joineral32-cengage** [comment]
@ebidel Despite the iron-selector change seeming like a likely suspect, rolling back to a previous version of that does not cause our tests to pass. I have been able to get our builds to go green by rolling Polymer back to 1.2.1 so I will probably just keep things on that version until I can get a chance to do a deeper root cause on what's actually making our tests fail with 1.2.2

**Comment by ebidel** [comment]
OK thanks for investigating.

**Comment by ebidel** [comment]
FYI. 1.2.3 is out

**Comment by ebidel** [comment]
@cdata. I take it back. The iron-selector change broke polyfilled browsers. We had to make changes to wait for the iron-items-changed event: https://github.com/googlecodelabs/codelab-components/pull/5

**Comment by JeremybellEU** [comment]
@ebidel all failing tests have been fixed, haven't they?

**Comment by ebidel** [comment]
@azakus will know

**Comment by azakus** [comment]
Polymer's tests are all green.

**Comment by joineral32-cengage** [comment]
Hi, just wanted to jump back in and point out that this problem, at least for me, turned out to be user error. We discovered several tests that were not correctly querying the local DOM (they were doing document.querySelector). After replacing those queries with correct ones, we were able to upgrade to 1.2.2 (and 1.2.3) without these test issues.

**Comment by drarmstr** [comment]
Upgrading to 1.2.3 didn't resolve the IE11 regression for me.  Still getting the `SCRIPT445: Object doesn't support this action` error.  Is 1.2.3 expected to resolve the issue or might there be some user error still that is exposed by changes since 1.2.1, which worked?

**Comment by TimvdLippe** [comment]
@drarmstr what version of webcomponentsjs is loaded? If I remember correctly, your issue should (presumably) be fixed in the latest version of webcomponentsjs.

**Comment by drarmstr** [comment]
@TimvdLippe Ah yes, that explains it.  I was working with a fork of webcomponents.js while waiting for a merge of webcomponents/webcomponentsjs#395.

**Comment by TimvdLippe** [comment]
@drarmstr Was your issue resolved? I assume the issue is unrelated to the specific version 1.2.2 so this issue can be closed.

**Comment by drarmstr** [comment]
@TimvdLippe  Yes, I confirmed that merging the latest webcomponents/webcomponentsjs changes into my branch for the webcomponents/webcomponentsjs#395 issue resolved everything.  The `<dom-repeat>` issue was also unrelated to this issue and we were able to get it resolved.

**Comment by sorvell** [comment]
Closing since all issues have been resolved.
