### ISSUE TITLE
Registration failed for type 'dom-module'/DuplicateDefinitionError: a type with name 'dom-module' is already registered

### ISSUE THREAD

**Issue by iSuslov** [Polymer/polymer#4134]
### Description
First of all it took about 6 hours to realize what causes this error. So thanks to me. 

**After build** error thrown when using any import other than `[entrypoint].html` in main `index.html` file.

In **Firefox 49.0.2** error looks like this:

> Error: DuplicateDefinitionError: a type with name 'dom-module' is already registered
> TypeError: Polymer.Base._getExtendedPrototype is not a function
> TypeError: this._desugarBehaviors is not a function

In **Chrome Version 54.0.2840.71 (64-bit)** looks like this:

>Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.
>Uncaught TypeError: Polymer.Base._getExtendedPrototype is not a function
>Uncaught TypeError: this._desugarBehaviors is not a function

#### Steps to Reproduce
1. Create a new application/[or clone this repo and skip next 2 steps](https://github.com/iSuslov/polymer-import-error-in-index.html)
2. Add import in main `index.html` like it says in the [flexbox docs](https://elements.polymer-project.org/guides/flex-layout) in **Example: using classes in the main document** section. Like that:
```html
<head>

  ...

  <link rel="import" href="bower_components/iron-flex-layout/iron-flex-layout-classes.html">

  ...

</head>
```
3. Add `iron-flex-layout-classes` in `polymer.json` `includeDependencies` property. Otherwise it won't pick this dependency up. 
4. Build with `polymer build`
5. Serve with `polymer serve` bundled/unbundled version of the app.
5. Get a lot of pain with the error above.

#### Expected Results
No error

#### Actual Results
Error. See above.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [ ] Safari 8 most probably yes
- [ ] IE 11  most probably yes

### Versions

- Polymer-cli:  v0.16.0, v0.17.0 
- Polymer:  v1.7.0 
- webcomponents: v0.7.23

**Comment by fairsayan** [comment]
I'm experiencing the same issue, even if I'm not 100% sure it's the same reason.
https://by-wink-timeshift.firebaseapp.com/credits works fine on Chrome Version 55.0.2883.95, but it fails on Safari and Firefox:
```javascript
Error: DuplicateDefinitionError: a type with name 'dom-module' is already registered  webcomponents-lite.min.js:2:3560

https://by-wink-timeshift.firebaseapp.com/bower_components/webcomponentsjs/webcomponents-lite.min.js:2:3560
	<anonimo> https://by-wink-timeshift.firebaseapp.com/bower_components/polymer/polymer-micro.html.js:1:7001
	<anonimo> https://by-wink-timeshift.firebaseapp.com/bower_components/polymer/polymer-micro.html.js:1:6215
```

it seems to be something related with webcomponentsjs that Chrome doesn't use because it supports WebComponents nativly

**Comment by RyanCopley** [comment]
We're receiving this exact same error after including an internal fork of `app-localized-behavior` to one of our tests.

**Comment by RyanCopley** [comment]
```
Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.
    at http://localhost:8080/components/client/vendor/bower/polymer/polymer-micro.html:360:10
    at http://localhost:8080/components/client/vendor/bower/polymer/polymer-micro.html:375:2
(anonymous) @ polymer-micro.html:360
(anonymous) @ polymer-micro.html:375
polymer-micro.html:68 Uncaught TypeError: Polymer.Base._getExtendedPrototype is not a function
    at desugar (polymer-micro.html:68)
    at window.Polymer (polymer-micro.html:55)
    at polymer.html:4142
    at polymer.html:4244
desugar @ polymer-micro.html:68
window.Polymer @ polymer-micro.html:55
(anonymous) @ polymer.html:4142
(anonymous) @ polymer.html:4244
polymer-micro.html:184 Uncaught TypeError: this._desugarBehaviors is not a function
    at HTMLElement.registerCallback (polymer-micro.html:184)
    at desugar (polymer-micro.html:71)
    at window.Polymer (polymer-micro.html:55)
    at iron-request.html:24
registerCallback @ polymer-micro.html:184
desugar @ polymer-micro.html:71
window.Polymer @ polymer-micro.html:55
(anonymous) @ iron-request.html:24
polymer-micro.html:184 Uncaught TypeError: this._desugarBehaviors is not a function
    at HTMLElement.registerCallback (polymer-micro.html:184)
    at desugar (polymer-micro.html:71)
    at window.Polymer (polymer-micro.html:55)
    at iron-ajax.html:42
registerCallback @ polymer-micro.html:184
desugar @ polymer-micro.html:71
window.Polymer @ polymer-micro.html:55
(anonymous) @ iron-ajax.html:42
polymer-micro.html:184 Uncaught TypeError: this._desugarBehaviors is not a function
    at HTMLElement.registerCallback (polymer-micro.html:184)
    at desugar (polymer-micro.html:71)
    at window.Polymer (polymer-micro.html:55)
    at media-gallery-count.html:63
registerCallback @ polymer-micro.html:184
desugar @ polymer-micro.html:71
window.Polymer @ polymer-micro.html:55
(anonymous) @ media-gallery-count.html:63
console.js:65 
```

**Comment by fairsayan** [comment]
I solved my problem using the unbundled version...

**Comment by RyanCopley** [comment]
C&P from Slack:

```
arthur [6:01 PM]
That is usually a symptom of importing two different versions of Polymer (or rather, of importing Polymer using two different URLs so it doesn't get deduped). 
```

**Comment by justinfagnani** [comment]
@usergenic can you check this out with the new bundler?

**Comment by kumarvishal** [comment]
Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.

Same for me, will write back once I find a resolution for this issue.

**Comment by RyanCopley** [comment]
Make sure multiple copies of polymer are not being loaded via various imports.

**Comment by Sinjins** [comment]
I'm having the same problem here.  Any way around this in order to be able to serve the bundled version?

**Comment by marty331** [comment]
Anyone have a solution for this?  same issue here.

**Comment by web-padawan** [comment]
You need to check how you import `polymer`. If your entrypoint, usually `index.html`, loads `polymer.html` and then an app-shell element (say `my-app`) which loads `polymer.html` too, this could happen because polymer gets bundled to app-shell but also is being loaded from entrypoint, and those imports cannot be de-duplicated.
In general, if you are developing SPA, always include only app-shell element in `index.html` and after bundling you will be fine.

**Comment by arthurevans** [comment]
As @web-padawan said, the OP's problem can be solved by moving the import for `iron-flex-layout-classes` out of `index.html` into `demo-app.html` (and removing it from `includeDependencies`).

The `includeDependencies` is intended for things the analyzer can't discover, and should just copy over to the build folder. So it copies over `iron-flex-layout-classes.html`, which imports the (unbundled) Polymer. Meanwhile, the built `demo-app.html` ends up containing a bundled copy of Polymer.

**Comment by mkutny** [comment]
Luckily I stumbled upon this issue.

Having your explanation it's now obvious what's going on but I think it also would be wise to reflect it in your docs: https://www.polymer-project.org/1.0/toolbox/server

This is a kind of behavior which is pretty easy to cause but then it takes a lot of hard hours to find a reason.

**Comment by mgibas** [comment]
It will try to register Polymer once again if u forget to include a fragment in the `polymer.json` - which makes sense, analyzer/bundler has no chance to dedupe this import.

**Comment by web-padawan** [comment]
BTW, the previous comment by @mgibas makes sense because as of now, bundled version also contains unbundled dependencies.
/cc @usergenic who is aware of that `polymer-build` issue.

**Comment by mgibas** [comment]
true, I would spend way less time troubleshooting if I could not find these files in a build directory.

**Comment by MaxMommersteeg** [comment]
I'm facing the same issue when loading components from multiple sources (Web API 1 and Web API 2) into one webpage. Both use the same version of Polymer (V1.4), however the urls differ.

I can load components built with x-tag or "native (ES6)" ones from multiple different sources without any issues. Sadly my current approach can now not support Polymer and all nice existing web components built with Polmer like paper-elements and iron-elements.

Is this issue resolved in version 2.0 of Polymer, or should this issue also be labeled with 2.x? Is there syntax that allows me to check whether one of the components already imported Polymer and with that knowledge prevent other components from importing it more than once?

**Comment by TimvdLippe** [comment]
>  Is there syntax that allows me to check whether one of the components already imported Polymer and with that knowledge prevent other components from importing it more than once?

You can use [`customElements.get`](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/get) to get a reference (and thus detect if it exists) to an existing custom element definition.

I don't think we should try to let Polymer be allowed to load twice. A nicer way would be to have a descriptive error message which describes the issue (e.g. something along the lines of `Polymer has already been defined. Make sure you load Polymer once by deduplicating the load URLs`) instead of the non-descriptive vague `Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'.`

**Comment by osamamaruf** [comment]
> I don't think we should try to let Polymer be allowed to load twice. A nicer way would be to have a descriptive error message which describes the issue (e.g. something along the lines of Polymer has already been defined. Make sure you load Polymer once by deduplicating the load URLs) instead of the non-descriptive vague Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'.

This is not practical for enterprise applications. 

Consider the case where an application is a container of other applications (a very common enterprise app scenario). In such environments the other applications are being developed and hosted independently. Hence one cannot ensure that Polymer is loaded only once and thus the limitation of not loading it again is a blocker for enterprise adoption. 

This might be worked around by using `iframes` however Polymer should not force us to use them. Another workaround is to force all teams to load all common dependencies on say a CDN and include that in the container. However, again its a hack as it would kill application performance depending on the number of dependencies added on this central location so that de-duping works.

I think that https://github.com/w3c/webcomponents/issues/716 is a step in this direction however, at the  moment a fix for this is needed in polymer as adoption in WC might take a while.

**Comment by vikrantrathore** [comment]
I am experiencing same issue with polymer. Looks like polymer team and polymer project is dead now. Also lit-element and lit-html do not have serious support like vuejs or angular or react. So it seems like a deadend to work in polymer and web component eco-system. This issue has been open since 2017 and not one comment on how it will be handled or updated.

This is one of the reasons not to jump on web component bandwagon yet in spite of some adoption.

**Comment by arthurevans** [comment]
@vikrantrathore the Polymer library is in maintenance mode now. There are many comments on this bug already about things that could cause this issue in your code, and possible fixes. 

The Polymer team is alive and well and working on lit-html and LitElement, among other things. LitElement doesn't define any elements of its own, so you won't see this exact issue from LitElement. However, it's still possible to get an error like this by importing two versions of the same _component_, whether using LitElement or some other library.
