### ISSUE TITLE
Performance in Firefox

### ISSUE THREAD

**Issue by Mikanoshi** [Polymer/polymer#952]
I need to create ~700 paper-input fields, it takes 2-3 seconds in Chrome and all animations are still smooth, but in Firefox 33.1.1 it takes at least 7 seconds and degrades transition performance. Test page for 200 and 700 elements + paper-slider with slow animations:
http://sysprofile.ru/test.html?count=200
http://sysprofile.ru/test.html?count=700

Polyfills are that much slower than native implementation? Polymer is not working at all with dom.webcomponents.enabled flag...

**Comment by jmesserly** [comment]
fyi, this should be fixed in the https://github.com/Polymer/polymer/tree/0.8-preview branch

**Comment by Mikanoshi** [comment]
It requires something else? Because I import polymer.html and polymer-shadow.html and get an error
``TypeError: Polymer.mixin is not a function``

**Comment by jmesserly** [comment]
@Mikanoshi -- sorry, I should have clarified, that's a preview branch, there isn't docs yet about end user consumption. Was pointing out that a fix is on the way :)

but if you use polymer-shadow, you won't get a speedup. The idea is to avoid polymer-shadow if you need to create a huge DOM tree

**Comment by Mikanoshi** [comment]
I just can't install it to work at all :) also I'm using tons of polymer elements, will they work without that polymer-shadow? I thought they were using ShadowDOM.

**Comment by arthurevans** [comment]
Your current polymer elements (including existing versions of the core- and paper- elements) won't work with 0.8-preview. That release is not ready for public consumption yet.

**Comment by dencold** [comment]
Hey Arthur, any general ballpark for when 0.8 will be pushed out (days, weeks, months? :) Just trying to lay that into my development plans. Thanks so much! Really excited for the new release.

**Comment by arthurevans** [comment]
So, the official guidance from @mattsmcnulty (at Chrome DevSummit last year) was that there would be an official release of this branch in Q1, with a production-ready 1.0 slated to follow in Q2. As far as I know, that's still the case.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by Mikanoshi** [comment]
I moved from Polymer 0.5 to 1.2.3 and currently have 350 paper-inputs on one page.
Chrome/Opera - almost instant loading.
Firefox - 3-4 seconds, slightly less smooth animations, bearable.
IE11/EDGE/Maxthon - 9-10 seconds and animations become choppy.

**Comment by ebidel** [comment]
One `paper-input` has 14 children elements to help it do it's job. 14 * 350 = **4900 elements**. That's a lot of DOM to render on page load and that doesn't include anything else in your app. Presumably there is more stuff on the page?

Check out https://youtu.be/Yr84DpNaMfk?t=19m19s for an explanation and suggested workarounds.

FWIW, I ran `document.querySelectorAll('body /deep/ *').length` to figure out how many children a paper-input has.

**Comment by Mikanoshi** [comment]
350 paper-inputs, 20 paper-checkboxes, 15 paper-dropdown-menus, 15 paper-tooltips, 15 paper-ripples, paper-tabs with 3 tabs, 3 paper-dialogs, 10 paper-buttons and a couple of paper-textareas :)

I have 15 pages with elements, each page should be fully loaded when it becomes visible. I was using workaround above to dynamically switch between paper-inputs and regular inputs when page is opened and closed, but it still took 0.6-1s to render, I had to add a delay to prevent animation freezes during page switching.

Anyway, I wanted to get rid of it with Polymer 1.0+, because it has better performance, but paper elements now contain more elements, so resulting difference is not that big.
