### ISSUE TITLE
Uncaught TypeError: inst.notifyPath is not a function ( v1.0.7+ )

### ISSUE THREAD

**Issue by pdelanauze** [Polymer/polymer#2164]
I've been seeing errors like these every since upgrading from 1.0.6 to 1.0.7 ( applies to 1.0.8 as well ). 

Haven't been able to isolate this problem in a fresh project yet , hoping maybe someone looking at the stack trace will be able to see right away what the issue is .. 

and yeah , sorry for the screenshot .. couldn't think of a better way to share. Will do a bit more research to see if this is a common problem and try and isolate in a jsbin within the week 

![screen shot 2015-07-28 at 6 45 50 pm](https://cloud.githubusercontent.com/assets/224985/8945820/e6e9a998-3558-11e5-9161-84cc77aa2a80.png)

**Comment by pdelanauze** [comment]
#2068  ? not sure if it could be related ..

**Comment by kevinpschaaf** [comment]
Yes, if you could provide a jsBin repro, that would be the best.  Thanks!

**Comment by pdelanauze** [comment]
Just spent a few hours trying to reproduce this standalone , no luck .. guess its time to close this unless someone else experienced similar issues

**Comment by luccamordente** [comment]
I'm experiencing this as well, but could not reproduce standalone yet.

**Comment by luccamordente** [comment]
I don't have much knowledge of the Polymer internals, but I could figure out that this error happens when the instance `inst` in question is a placeholder. It's an object as simple as this: 
```javascript
{
  isPlaceholder: true,
  key: 10
}
```

This object is created in the [`_applySplicesArrayOrder` function](https://github.com/Polymer/polymer/blob/0f8483da48dc3747f3c4bdd439b95c4bce2897d7/src/lib/template/dom-repeat.html#L523) and is returned as one of the template instances in the [`_forwardParentPath` function](https://github.com/Polymer/polymer/blob/0f8483da48dc3747f3c4bdd439b95c4bce2897d7/src/lib/template/dom-repeat.html#L626)

I don't know if it's appropriate, not even if this object should be there, but as a quick fix, I put an `if` to ignore the placeholders:
```javascript
  _forwardParentPath: function (path, value) {
    this._instances.forEach(function (inst) {
      if (!inst.isPlaceholder) {
        inst.notifyPath(path, value, true);
      }
    }, this);
  },
```

I hope this helps you guys to figure out the solution.

**Comment by azakus** [comment]
Closed due to age, please reopen with a test case if this is still a problem.
