### PR TITLE
Move mixin to Base. Fixes #1911

### LINKED ISSUE #1911: polymer 1.0 Uncaught TypeError: this.mixin is not a function
We are using polymer for our some of the components in our hybrid app. When I upgrade polymer 0.5 to 1.0 I kept seeing this error message: 
polymer-micro.html:401  Uncaught TypeError: this.mixin is not a function

I have no idea what I did wrong. The components are working fine in the demo index files. When I load the component to my project, even just <paper-button> polymer was broken

### PR DESCRIPTION
**Pull request by kevinpschaaf**

### CODE REVIEW

**Comment by sorvell** [comment]
LGTM
