### ISSUE TITLE
iOS 8.1 safari TypeError: Object.setPrototypeOf(f,b.prototype)

### ISSUE THREAD

**Issue by baocang** [Polymer/polymer#5142]
#### Live Demo

https://jsbin.com/luhaxab/1/edit

https://glitch.com/edit/#!/polymer-repro?path=my-element.html:2:0

TypeError: undefined is not a function (evaluating 'Object.setPrototypeOf(f,b.prototype)')
#### Steps to Reproduce

1. Create `polymer init polymer-2-application` with name `demo-app`
2. Serve `polymer serve` 
3. Open in iOS 8.1 safari

#### Expected Results

Display `Hello demo-app!`

#### Actual Results

TypeError: undefined is not a function (evaluating 'Object.setPrototypeOf(f,b.prototype)')

### Browsers Affected

- [x] iOS 8.1 Safari

### Versions

- Polymer: v2.5.0
- webcomponents: v1.1.0

**Comment by baocang** [comment]
FYI:  i write this code fixed it. but I think this is not a good idea.

```javascript
if (!Object.setPrototypeOf) {
  Object.setPrototypeOf = function (obj, proto) {
    obj.__proto__ = proto;
  };
}
if (!window.performance) {
  window.performance = {
    timeOrigin: new Date.valueOf()
  };
} 
if (!window.performance.now) {
  window.performance.now = function() {
    return new Date().valueOf() - window.performance.timeOrigin;
  }
}
```

**Comment by baocang** [comment]
There a lot errors can fixed by core-js, why do not add some options for support core-js with polymer-cli

![image](https://user-images.githubusercontent.com/16043697/37083774-8ba612ac-222b-11e8-86fb-25e874f7ad6a.png)

**Comment by TimvdLippe** [comment]
Per https://www.polymer-project.org/2.0/docs/browsers we support iOS Safari 9+, which does not include 8.1. I think that we would only consider supporting older versions of iOS Safari in the corresponding polyfills, however I am not aware of any plans for doing so.

Please open a PR on the webcomponents polyfill if you are able to make a custom element work on iOS Safari 8.1 with minimal changes. We can continue the discussion over there.
